#!/usr/bin/env python3
"""Emit a complete `MutilatedChessboard<2k>.lean` instance module for the verified
PB backend, for a 2k x 2k board minus its two opposite (same-colour) corners.

This generalises the hand-written 4x4 `MutilatedChessboard.lean` to arbitrary k:
the geometry (placements, per-cell exact-cover constraints) is the same as
`pbgen._mutilated_geometry`, so the emitted `encodeLinear mcSig mcLin` OPB is
byte-for-byte identical to `pbgen.mutilated_opb(k)` (validated at k=2).

Usage:  uv run python gen_mutilated_lean.py <k> <kernel_proof_file> > Module.lean
"""

from __future__ import annotations

import sys

import pbgen


def gen(k: int, cert: str) -> str:
    nplace, covers = pbgen._mutilated_geometry(k)
    board = 2 * k
    ns = f"MutilatedChessboard{board}"
    V = f"_root_.Vector (HomogeneousVarIndex {nplace})"

    # --- the CSP: per-present-cell exactly-one over its covering placements ---
    cell_lines = []
    for (r, c), cov in covers:
        arr = ", ".join(str(p) for p in cov)
        cell_lines.append(
            f"    -- cell ({r}, {c})\n"
            f"    sum_eq (⟨#[{arr}], rfl⟩ : {V} {len(cov)}) 1")
    csp_body = ",\n".join(cell_lines)

    # --- mcLin: two linear <= halves per cell ---
    lin_lines = []
    for (_r, _c), cov in covers:
        pos = ", ".join(f"(1, ({p} : Fin {nplace}))" for p in cov)
        neg = ", ".join(f"(-1, ({p} : Fin {nplace}))" for p in cov)
        lin_lines.append(f"    ([{pos}], 1)")
        lin_lines.append(f"    ([{neg}], -1)")
    lin_body = ",\n".join(lin_lines)

    ncell = len(covers)
    hnames = [f"h{i}" for i in range(ncell)]
    obtain = "⟨_hbounds, " + ", ".join(hnames) + ", _⟩"
    have_lines = []
    for i, ((_r, _c), cov) in enumerate(covers):
        arr = ", ".join(str(p) for p in cov)
        have_lines.append(f"  have hs{i} := sum_eq_sat ⟨#[{arr}], rfl⟩ 1 a h{i}")
        have_lines.append(f"  simp at hs{i}")
    have_body = "\n".join(have_lines)
    rcases = " | ".join("rfl" for _ in range(2 * ncell))
    hslist = ", ".join(f"hs{i}" for i in range(ncell))

    cert_indented = cert.rstrip("\n")

    return f'''import CSP.L2S.Backends.PB.Adapter
import CSP.L2S.Constraints

namespace CSP.L2S.PB.{ns}

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — end-to-end verified UNSAT for the {board} × {board} mutilated chessboard

A scaling checkpoint (see `docs/SCALING.md`) generalising the 4 × 4 instance in
`MutilatedChessboard.lean` to a {board} × {board} board with its two opposite
(same-colour) corners removed.  The colour-counting argument is unchanged: each
domino covers one black and one white cell, but removing two same-colour corners
leaves a colour imbalance of 2, so no domino tiling exists.

The encoding is the same exact-cover order encoding: one Boolean placement
variable per pair of orthogonally adjacent remaining cells ({nplace} placements),
a per-cell `sum_eq … = 1`, and the clean `unsat_of_pb` linear-`≤` spine.  The
mutilated chessboard is exponentially hard for resolution (Alekhnovich) but the
cutting-planes certificate is the linear colour count — here a {len(cert)}-char
kernel proof.  Generated by `scripts/scaling/gen_mutilated_lean.py`.
-/

/-- The {nplace} domino-placement variables (one per orthogonally adjacent pair of
    remaining cells), each in `{{0,1}}`, with a per-cell exactly-one constraint. -/
def mutilatedChessboard{board} : HomogeneousCSP :=
  ⟨{nplace}, ((List.finRange {nplace}).map (fun i => bound i 0 1))
      ++ [
{csp_body}
      ]⟩

/-- The PB signature: {nplace} Boolean placement variables over `{{0,1}}`. -/
def mcSig : CSPSig where
  nInt := {nplace}
  nBool := 0
  nAux := 0
  values := fun _ => domainValues 0 1
  sorted := fun _ => domainValues_sorted 0 1
  nonempty := fun _ => domainValues_nonempty (by norm_num)

/-- The linear `≤` core fed to `unsat_of_pb`: the two `≤` halves of each cell's
    exactly-one constraint. -/
def mcLin : List (List (Int × Fin {nplace}) × Int) :=
  [
{lin_body}
  ]

/-- Every placement variable has its `bound 0 1` constraint in the CSP. -/
theorem mc_hbound (i : Fin mutilatedChessboard{board}.num_vars) :
    bound i 0 1 ∈ mutilatedChessboard{board}.constraints := by
  show bound i 0 1 ∈ ((List.finRange {nplace}).map (fun i => bound i 0 1)) ++ _
  apply List.mem_append_left
  exact List.mem_map.mpr ⟨i, List.mem_finRange i, rfl⟩

set_option maxHeartbeats 1600000 in
/-- Every linear `≤` fact in `mcLin` follows from any solution (each cell's
    `sum_eq … = 1` gives `Σ covering placements = 1`, whose two `≤` halves are the
    `mcLin` entries).  The heartbeat bump accommodates the {ncell}-cell ×
    2-half mechanical case split (larger than the 4 × 4 instance's). -/
theorem mc_hlin (a : HomogeneousAssignment {nplace})
    (hsol : mutilatedChessboard{board}.isSolution a) :
    ∀ c ∈ mcLin, (c.1.map (fun p => p.1 * a p.2)).sum ≤ c.2 := by
  unfold HomogeneousCSP.isSolution mutilatedChessboard{board} at hsol
  simp only [List.forall_mem_append, List.forall_mem_cons] at hsol
  obtain {obtain} := hsol
{have_body}
  intro c hc
  simp only [mcLin, List.mem_cons, List.not_mem_nil, or_false] at hc
  rcases hc with {rcases} <;>
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil] <;>
    linarith [{hslist}]

/-- The veripb-elaborated kernel proof of UNSAT for `mcLin`'s OPB serialization
    (RoundingSat + veripb; both untrusted).  The single `pol` step is the
    colour-counting linear combination. -/
def mcKernelProof : String :=
"{cert_indented}
"

/-- The PB encoding of the {board} × {board} mutilated chessboard's exact-cover
    query is unsatisfiable — kernel-checked through PBLean's verified reflection
    checker (`native_decide`; RoundingSat / veripb / serializer untrusted). -/
theorem mc_formulaUnsat :
    VeriPB.Reflect.formulaUnsat
      ((encodeLinear mcSig mcLin).toArray.map PBConstr.toNatConstr) :=
  VeriPB.Reflect.checkProof_sound _ {nplace} mcKernelProof (by native_decide)

/-- **End-to-end mutilated-chessboard UNSAT ({board} × {board}).** A {board} × {board}
    board minus two opposite (same-colour) corners cannot be tiled by dominoes,
    via the verified PB pipeline and the committed colour-counting certificate. -/
theorem mutilated_chessboard_{board}_unsat : ¬ mutilatedChessboard{board}.isSatisfiable := by
  refine unsat_of_pb mutilatedChessboard{board} (fun _ => 0) (fun _ => 1)
    (fun _ => by norm_num) mc_hbound mcLin mc_hlin ?_
  show VeriPB.Reflect.formulaUnsat
    ((encodeLinear mcSig mcLin).toArray.map PBConstr.toNatConstr)
  exact mc_formulaUnsat

end CSP.L2S.PB.{ns}
'''


if __name__ == "__main__":
    k = int(sys.argv[1])
    cert = open(sys.argv[2]).read()
    sys.stdout.write(gen(k, cert))
