import CSP.L2S.Backends.PB.GenericEncode
import CSP.L2S.Tests.lean.«02_color»

namespace CSP.L2S.PB.ForbiddenColoring

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — end-to-end verified UNSAT for forbidden-colour `k2_forbidden`

`k2_forbidden` (`Tests/lean/02_color.lean`) colours the single edge **K₂** with
two colours `{1,2}`, forbids colour 1 at both endpoints (`not_equals_const` per
vertex), and requires the endpoints to differ (`not_equal`) — so both must be 2,
contradiction.  Discharged by a single `csp_unsat` over its committed certificate
(`certs/k2_forbidden.pbp`, regenerated by `scripts/gen_cert.sh`); axioms clean.
-/

/-- **`k2_forbidden` is unsatisfiable.** -/
theorem k2_forbidden_unsat : ¬ k2_forbidden.isSatisfiableInt :=
  csp_unsat_file k2_forbidden 2 "certs/k2_forbidden.pbp"

end CSP.L2S.PB.ForbiddenColoring
