import CSP.L2S.Backends.PB.Adapter
import CSP.L2S.Constraints

namespace CSP.L2S.PB.MutilatedChessboard6

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — end-to-end verified UNSAT for the 6 × 6 mutilated chessboard

A scaling checkpoint (see `docs/SCALING.md`) generalising the 4 × 4 instance in
`MutilatedChessboard.lean` to a 6 × 6 board with its two opposite
(same-colour) corners removed.  The colour-counting argument is unchanged: each
domino covers one black and one white cell, but removing two same-colour corners
leaves a colour imbalance of 2, so no domino tiling exists.

The encoding is the same exact-cover order encoding: one Boolean placement
variable per pair of orthogonally adjacent remaining cells (56 placements),
a per-cell `sum_eq … = 1`, and the clean `unsat_of_pb` linear-`≤` spine.  The
mutilated chessboard is exponentially hard for resolution (Alekhnovich) but the
cutting-planes certificate is the linear colour count — here a 937-char
kernel proof.  Generated by `scripts/scaling/gen_mutilated_lean.py`.
-/

/-- The 56 domino-placement variables (one per orthogonally adjacent pair of
    remaining cells), each in `{0,1}`, with a per-cell exactly-one constraint. -/
def mutilatedChessboard6 : IntCSP :=
  ⟨56, ((List.finRange 56).map (fun i => bound i 0 1))
      ++ [
    -- cell (0, 1)
    sum_eq (⟨#[0, 1], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (0, 2)
    sum_eq (⟨#[0, 2, 3], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (0, 3)
    sum_eq (⟨#[2, 4, 5], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (0, 4)
    sum_eq (⟨#[4, 6, 7], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (0, 5)
    sum_eq (⟨#[6, 8], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (1, 0)
    sum_eq (⟨#[9, 10], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (1, 1)
    sum_eq (⟨#[1, 9, 11, 12], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 2)
    sum_eq (⟨#[3, 11, 13, 14], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 3)
    sum_eq (⟨#[5, 13, 15, 16], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 4)
    sum_eq (⟨#[7, 15, 17, 18], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 5)
    sum_eq (⟨#[8, 17, 19], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (2, 0)
    sum_eq (⟨#[10, 20, 21], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (2, 1)
    sum_eq (⟨#[12, 20, 22, 23], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 2)
    sum_eq (⟨#[14, 22, 24, 25], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 3)
    sum_eq (⟨#[16, 24, 26, 27], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 4)
    sum_eq (⟨#[18, 26, 28, 29], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 5)
    sum_eq (⟨#[19, 28, 30], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (3, 0)
    sum_eq (⟨#[21, 31, 32], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (3, 1)
    sum_eq (⟨#[23, 31, 33, 34], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 2)
    sum_eq (⟨#[25, 33, 35, 36], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 3)
    sum_eq (⟨#[27, 35, 37, 38], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 4)
    sum_eq (⟨#[29, 37, 39, 40], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 5)
    sum_eq (⟨#[30, 39, 41], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (4, 0)
    sum_eq (⟨#[32, 42, 43], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (4, 1)
    sum_eq (⟨#[34, 42, 44, 45], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 2)
    sum_eq (⟨#[36, 44, 46, 47], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 3)
    sum_eq (⟨#[38, 46, 48, 49], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 4)
    sum_eq (⟨#[40, 48, 50, 51], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 5)
    sum_eq (⟨#[41, 50], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (5, 0)
    sum_eq (⟨#[43, 52], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (5, 1)
    sum_eq (⟨#[45, 52, 53], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (5, 2)
    sum_eq (⟨#[47, 53, 54], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (5, 3)
    sum_eq (⟨#[49, 54, 55], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (5, 4)
    sum_eq (⟨#[51, 55], rfl⟩ : _root_.Vector (VarType 56) 2) 1
      ]⟩

/-- The PB signature: 56 Boolean placement variables over `{0,1}`. -/
def mcSig : CSPSig where
  nInt := 56
  nBool := 0
  nAux := 0
  values := fun _ => domainValues 0 1
  sorted := fun _ => domainValues_sorted 0 1
  nonempty := fun _ => domainValues_nonempty (by norm_num)

/-- The linear `≤` core fed to `unsat_of_pb`: the two `≤` halves of each cell's
    exactly-one constraint. -/
def mcLin : List (List (Int × Fin 56) × Int) :=
  [
    ([(1, (0 : Fin 56)), (1, (1 : Fin 56))], 1),
    ([(-1, (0 : Fin 56)), (-1, (1 : Fin 56))], -1),
    ([(1, (0 : Fin 56)), (1, (2 : Fin 56)), (1, (3 : Fin 56))], 1),
    ([(-1, (0 : Fin 56)), (-1, (2 : Fin 56)), (-1, (3 : Fin 56))], -1),
    ([(1, (2 : Fin 56)), (1, (4 : Fin 56)), (1, (5 : Fin 56))], 1),
    ([(-1, (2 : Fin 56)), (-1, (4 : Fin 56)), (-1, (5 : Fin 56))], -1),
    ([(1, (4 : Fin 56)), (1, (6 : Fin 56)), (1, (7 : Fin 56))], 1),
    ([(-1, (4 : Fin 56)), (-1, (6 : Fin 56)), (-1, (7 : Fin 56))], -1),
    ([(1, (6 : Fin 56)), (1, (8 : Fin 56))], 1),
    ([(-1, (6 : Fin 56)), (-1, (8 : Fin 56))], -1),
    ([(1, (9 : Fin 56)), (1, (10 : Fin 56))], 1),
    ([(-1, (9 : Fin 56)), (-1, (10 : Fin 56))], -1),
    ([(1, (1 : Fin 56)), (1, (9 : Fin 56)), (1, (11 : Fin 56)), (1, (12 : Fin 56))], 1),
    ([(-1, (1 : Fin 56)), (-1, (9 : Fin 56)), (-1, (11 : Fin 56)), (-1, (12 : Fin 56))], -1),
    ([(1, (3 : Fin 56)), (1, (11 : Fin 56)), (1, (13 : Fin 56)), (1, (14 : Fin 56))], 1),
    ([(-1, (3 : Fin 56)), (-1, (11 : Fin 56)), (-1, (13 : Fin 56)), (-1, (14 : Fin 56))], -1),
    ([(1, (5 : Fin 56)), (1, (13 : Fin 56)), (1, (15 : Fin 56)), (1, (16 : Fin 56))], 1),
    ([(-1, (5 : Fin 56)), (-1, (13 : Fin 56)), (-1, (15 : Fin 56)), (-1, (16 : Fin 56))], -1),
    ([(1, (7 : Fin 56)), (1, (15 : Fin 56)), (1, (17 : Fin 56)), (1, (18 : Fin 56))], 1),
    ([(-1, (7 : Fin 56)), (-1, (15 : Fin 56)), (-1, (17 : Fin 56)), (-1, (18 : Fin 56))], -1),
    ([(1, (8 : Fin 56)), (1, (17 : Fin 56)), (1, (19 : Fin 56))], 1),
    ([(-1, (8 : Fin 56)), (-1, (17 : Fin 56)), (-1, (19 : Fin 56))], -1),
    ([(1, (10 : Fin 56)), (1, (20 : Fin 56)), (1, (21 : Fin 56))], 1),
    ([(-1, (10 : Fin 56)), (-1, (20 : Fin 56)), (-1, (21 : Fin 56))], -1),
    ([(1, (12 : Fin 56)), (1, (20 : Fin 56)), (1, (22 : Fin 56)), (1, (23 : Fin 56))], 1),
    ([(-1, (12 : Fin 56)), (-1, (20 : Fin 56)), (-1, (22 : Fin 56)), (-1, (23 : Fin 56))], -1),
    ([(1, (14 : Fin 56)), (1, (22 : Fin 56)), (1, (24 : Fin 56)), (1, (25 : Fin 56))], 1),
    ([(-1, (14 : Fin 56)), (-1, (22 : Fin 56)), (-1, (24 : Fin 56)), (-1, (25 : Fin 56))], -1),
    ([(1, (16 : Fin 56)), (1, (24 : Fin 56)), (1, (26 : Fin 56)), (1, (27 : Fin 56))], 1),
    ([(-1, (16 : Fin 56)), (-1, (24 : Fin 56)), (-1, (26 : Fin 56)), (-1, (27 : Fin 56))], -1),
    ([(1, (18 : Fin 56)), (1, (26 : Fin 56)), (1, (28 : Fin 56)), (1, (29 : Fin 56))], 1),
    ([(-1, (18 : Fin 56)), (-1, (26 : Fin 56)), (-1, (28 : Fin 56)), (-1, (29 : Fin 56))], -1),
    ([(1, (19 : Fin 56)), (1, (28 : Fin 56)), (1, (30 : Fin 56))], 1),
    ([(-1, (19 : Fin 56)), (-1, (28 : Fin 56)), (-1, (30 : Fin 56))], -1),
    ([(1, (21 : Fin 56)), (1, (31 : Fin 56)), (1, (32 : Fin 56))], 1),
    ([(-1, (21 : Fin 56)), (-1, (31 : Fin 56)), (-1, (32 : Fin 56))], -1),
    ([(1, (23 : Fin 56)), (1, (31 : Fin 56)), (1, (33 : Fin 56)), (1, (34 : Fin 56))], 1),
    ([(-1, (23 : Fin 56)), (-1, (31 : Fin 56)), (-1, (33 : Fin 56)), (-1, (34 : Fin 56))], -1),
    ([(1, (25 : Fin 56)), (1, (33 : Fin 56)), (1, (35 : Fin 56)), (1, (36 : Fin 56))], 1),
    ([(-1, (25 : Fin 56)), (-1, (33 : Fin 56)), (-1, (35 : Fin 56)), (-1, (36 : Fin 56))], -1),
    ([(1, (27 : Fin 56)), (1, (35 : Fin 56)), (1, (37 : Fin 56)), (1, (38 : Fin 56))], 1),
    ([(-1, (27 : Fin 56)), (-1, (35 : Fin 56)), (-1, (37 : Fin 56)), (-1, (38 : Fin 56))], -1),
    ([(1, (29 : Fin 56)), (1, (37 : Fin 56)), (1, (39 : Fin 56)), (1, (40 : Fin 56))], 1),
    ([(-1, (29 : Fin 56)), (-1, (37 : Fin 56)), (-1, (39 : Fin 56)), (-1, (40 : Fin 56))], -1),
    ([(1, (30 : Fin 56)), (1, (39 : Fin 56)), (1, (41 : Fin 56))], 1),
    ([(-1, (30 : Fin 56)), (-1, (39 : Fin 56)), (-1, (41 : Fin 56))], -1),
    ([(1, (32 : Fin 56)), (1, (42 : Fin 56)), (1, (43 : Fin 56))], 1),
    ([(-1, (32 : Fin 56)), (-1, (42 : Fin 56)), (-1, (43 : Fin 56))], -1),
    ([(1, (34 : Fin 56)), (1, (42 : Fin 56)), (1, (44 : Fin 56)), (1, (45 : Fin 56))], 1),
    ([(-1, (34 : Fin 56)), (-1, (42 : Fin 56)), (-1, (44 : Fin 56)), (-1, (45 : Fin 56))], -1),
    ([(1, (36 : Fin 56)), (1, (44 : Fin 56)), (1, (46 : Fin 56)), (1, (47 : Fin 56))], 1),
    ([(-1, (36 : Fin 56)), (-1, (44 : Fin 56)), (-1, (46 : Fin 56)), (-1, (47 : Fin 56))], -1),
    ([(1, (38 : Fin 56)), (1, (46 : Fin 56)), (1, (48 : Fin 56)), (1, (49 : Fin 56))], 1),
    ([(-1, (38 : Fin 56)), (-1, (46 : Fin 56)), (-1, (48 : Fin 56)), (-1, (49 : Fin 56))], -1),
    ([(1, (40 : Fin 56)), (1, (48 : Fin 56)), (1, (50 : Fin 56)), (1, (51 : Fin 56))], 1),
    ([(-1, (40 : Fin 56)), (-1, (48 : Fin 56)), (-1, (50 : Fin 56)), (-1, (51 : Fin 56))], -1),
    ([(1, (41 : Fin 56)), (1, (50 : Fin 56))], 1),
    ([(-1, (41 : Fin 56)), (-1, (50 : Fin 56))], -1),
    ([(1, (43 : Fin 56)), (1, (52 : Fin 56))], 1),
    ([(-1, (43 : Fin 56)), (-1, (52 : Fin 56))], -1),
    ([(1, (45 : Fin 56)), (1, (52 : Fin 56)), (1, (53 : Fin 56))], 1),
    ([(-1, (45 : Fin 56)), (-1, (52 : Fin 56)), (-1, (53 : Fin 56))], -1),
    ([(1, (47 : Fin 56)), (1, (53 : Fin 56)), (1, (54 : Fin 56))], 1),
    ([(-1, (47 : Fin 56)), (-1, (53 : Fin 56)), (-1, (54 : Fin 56))], -1),
    ([(1, (49 : Fin 56)), (1, (54 : Fin 56)), (1, (55 : Fin 56))], 1),
    ([(-1, (49 : Fin 56)), (-1, (54 : Fin 56)), (-1, (55 : Fin 56))], -1),
    ([(1, (51 : Fin 56)), (1, (55 : Fin 56))], 1),
    ([(-1, (51 : Fin 56)), (-1, (55 : Fin 56))], -1)
  ]

/-- Every placement variable has its `bound 0 1` constraint in the CSP. -/
theorem mc_hbound (i : Fin mutilatedChessboard6.num_vars) :
    bound i 0 1 ∈ mutilatedChessboard6.constraints := by
  show bound i 0 1 ∈ ((List.finRange 56).map (fun i => bound i 0 1)) ++ _
  apply List.mem_append_left
  exact List.mem_map.mpr ⟨i, List.mem_finRange i, rfl⟩

set_option maxHeartbeats 1600000 in
/-- Every linear `≤` fact in `mcLin` follows from any solution (each cell's
    `sum_eq … = 1` gives `Σ covering placements = 1`, whose two `≤` halves are the
    `mcLin` entries).  The heartbeat bump accommodates the 34-cell ×
    2-half mechanical case split (larger than the 4 × 4 instance's). -/
theorem mc_hlin (a : IntAssignment 56)
    (hsol : mutilatedChessboard6.isSolutionInt a) :
    ∀ c ∈ mcLin, (c.1.map (fun p => p.1 * a p.2)).sum ≤ c.2 := by
  unfold IntCSP.isSolutionInt mutilatedChessboard6 at hsol
  simp only [List.forall_mem_append, List.forall_mem_cons] at hsol
  obtain ⟨_hbounds, h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, h14, h15, h16, h17, h18, h19, h20, h21, h22, h23, h24, h25, h26, h27, h28, h29, h30, h31, h32, h33, _⟩ := hsol
  have hs0 := sum_eq_sat ⟨#[0, 1], rfl⟩ 1 a h0
  simp at hs0
  have hs1 := sum_eq_sat ⟨#[0, 2, 3], rfl⟩ 1 a h1
  simp at hs1
  have hs2 := sum_eq_sat ⟨#[2, 4, 5], rfl⟩ 1 a h2
  simp at hs2
  have hs3 := sum_eq_sat ⟨#[4, 6, 7], rfl⟩ 1 a h3
  simp at hs3
  have hs4 := sum_eq_sat ⟨#[6, 8], rfl⟩ 1 a h4
  simp at hs4
  have hs5 := sum_eq_sat ⟨#[9, 10], rfl⟩ 1 a h5
  simp at hs5
  have hs6 := sum_eq_sat ⟨#[1, 9, 11, 12], rfl⟩ 1 a h6
  simp at hs6
  have hs7 := sum_eq_sat ⟨#[3, 11, 13, 14], rfl⟩ 1 a h7
  simp at hs7
  have hs8 := sum_eq_sat ⟨#[5, 13, 15, 16], rfl⟩ 1 a h8
  simp at hs8
  have hs9 := sum_eq_sat ⟨#[7, 15, 17, 18], rfl⟩ 1 a h9
  simp at hs9
  have hs10 := sum_eq_sat ⟨#[8, 17, 19], rfl⟩ 1 a h10
  simp at hs10
  have hs11 := sum_eq_sat ⟨#[10, 20, 21], rfl⟩ 1 a h11
  simp at hs11
  have hs12 := sum_eq_sat ⟨#[12, 20, 22, 23], rfl⟩ 1 a h12
  simp at hs12
  have hs13 := sum_eq_sat ⟨#[14, 22, 24, 25], rfl⟩ 1 a h13
  simp at hs13
  have hs14 := sum_eq_sat ⟨#[16, 24, 26, 27], rfl⟩ 1 a h14
  simp at hs14
  have hs15 := sum_eq_sat ⟨#[18, 26, 28, 29], rfl⟩ 1 a h15
  simp at hs15
  have hs16 := sum_eq_sat ⟨#[19, 28, 30], rfl⟩ 1 a h16
  simp at hs16
  have hs17 := sum_eq_sat ⟨#[21, 31, 32], rfl⟩ 1 a h17
  simp at hs17
  have hs18 := sum_eq_sat ⟨#[23, 31, 33, 34], rfl⟩ 1 a h18
  simp at hs18
  have hs19 := sum_eq_sat ⟨#[25, 33, 35, 36], rfl⟩ 1 a h19
  simp at hs19
  have hs20 := sum_eq_sat ⟨#[27, 35, 37, 38], rfl⟩ 1 a h20
  simp at hs20
  have hs21 := sum_eq_sat ⟨#[29, 37, 39, 40], rfl⟩ 1 a h21
  simp at hs21
  have hs22 := sum_eq_sat ⟨#[30, 39, 41], rfl⟩ 1 a h22
  simp at hs22
  have hs23 := sum_eq_sat ⟨#[32, 42, 43], rfl⟩ 1 a h23
  simp at hs23
  have hs24 := sum_eq_sat ⟨#[34, 42, 44, 45], rfl⟩ 1 a h24
  simp at hs24
  have hs25 := sum_eq_sat ⟨#[36, 44, 46, 47], rfl⟩ 1 a h25
  simp at hs25
  have hs26 := sum_eq_sat ⟨#[38, 46, 48, 49], rfl⟩ 1 a h26
  simp at hs26
  have hs27 := sum_eq_sat ⟨#[40, 48, 50, 51], rfl⟩ 1 a h27
  simp at hs27
  have hs28 := sum_eq_sat ⟨#[41, 50], rfl⟩ 1 a h28
  simp at hs28
  have hs29 := sum_eq_sat ⟨#[43, 52], rfl⟩ 1 a h29
  simp at hs29
  have hs30 := sum_eq_sat ⟨#[45, 52, 53], rfl⟩ 1 a h30
  simp at hs30
  have hs31 := sum_eq_sat ⟨#[47, 53, 54], rfl⟩ 1 a h31
  simp at hs31
  have hs32 := sum_eq_sat ⟨#[49, 54, 55], rfl⟩ 1 a h32
  simp at hs32
  have hs33 := sum_eq_sat ⟨#[51, 55], rfl⟩ 1 a h33
  simp at hs33
  intro c hc
  simp only [mcLin, List.mem_cons, List.not_mem_nil, or_false] at hc
  rcases hc with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil] <;>
    linarith [hs0, hs1, hs2, hs3, hs4, hs5, hs6, hs7, hs8, hs9, hs10, hs11, hs12, hs13, hs14, hs15, hs16, hs17, hs18, hs19, hs20, hs21, hs22, hs23, hs24, hs25, hs26, hs27, hs28, hs29, hs30, hs31, hs32, hs33]

/-- The veripb-elaborated kernel proof of UNSAT for `mcLin`'s OPB serialization
    (RoundingSat + veripb; both untrusted).  The single `pol` step is the
    colour-counting linear combination. -/
def mcKernelProof : String :=
"pseudo-Boolean proof version 3.0
f 68;
rup >= 0 : ~ ;
pol 69 2 1000000000000000 * + 3 1000000000000000 * + 6 1000000000000000 * + 7 1000000000000000 * + 10 1000000000000000 * + 12 1000000000000000 * + 13 1000000000000000 * + 16 1000000000000000 * + 17 1000000000000000 * + 20 1000000000000000 * + 21 1000000000000000 * + 23 1000000000000000 * + 26 1000000000000000 * + 27 1000000000000000 * + 30 1000000000000000 * + 31 1000000000000000 * + 34 1000000000000000 * + 36 1000000000000000 * + 37 1000000000000000 * + 40 1000000000000000 * + 41 1000000000000000 * + 44 1000000000000000 * + 45 1000000000000000 * + 47 1000000000000000 * + 50 1000000000000000 * + 51 1000000000000000 * + 54 1000000000000000 * + 55 1000000000000000 * + 58 1000000000000000 * + 60 1000000000000000 * + 61 1000000000000000 * + 64 1000000000000000 * + 65 1000000000000000 * + 68 1000000000000000 * +;
output NONE ;
conclusion UNSAT : 70;
end pseudo-Boolean proof;
"

/-- The PB encoding of the 6 × 6 mutilated chessboard's exact-cover
    query is unsatisfiable — kernel-checked through PBLean's verified reflection
    checker (`native_decide`; RoundingSat / veripb / serializer untrusted). -/
theorem mc_formulaUnsat :
    VeriPB.Reflect.formulaUnsat
      ((encodeLinear mcSig mcLin).toArray.map PBConstr.toNatConstr) :=
  VeriPB.Reflect.checkProof_sound _ 56 mcKernelProof (by native_decide)

/-- **End-to-end mutilated-chessboard UNSAT (6 × 6).** A 6 × 6
    board minus two opposite (same-colour) corners cannot be tiled by dominoes,
    via the verified PB pipeline and the committed colour-counting certificate. -/
theorem mutilated_chessboard_6_unsat : ¬ mutilatedChessboard6.isSatisfiableInt := by
  refine unsat_of_pb mutilatedChessboard6 (fun _ => 0) (fun _ => 1)
    (fun _ => by norm_num) mc_hbound mcLin mc_hlin ?_
  show VeriPB.Reflect.formulaUnsat
    ((encodeLinear mcSig mcLin).toArray.map PBConstr.toNatConstr)
  exact mc_formulaUnsat

end CSP.L2S.PB.MutilatedChessboard6
