import CSP.L2S.Backends.PB.GenericEncode
import CSP.L2S.Constraints

namespace CSP.L2S.PB.MutilatedChessboard6

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — end-to-end verified UNSAT for the 6 × 6 mutilated chessboard

A scaling checkpoint (see `docs/SCALING.md`) generalising the 4 × 4 instance in
`MutilatedChessboard.lean` to a 6 × 6 board with its two opposite
(same-colour) corners removed.  The colour-counting argument is unchanged: each
domino covers one black and one white cell, but removing two same-colour corners
leaves a colour imbalance of 2, so no domino tiling exists.

The encoding is the same exact-cover order encoding: one Boolean placement
variable per pair of orthogonally adjacent remaining cells (56 placements)
and a per-cell `sum_eq … = 1`, discharged by a single application of the generic
`csp_unsat` theorem over the committed certificate `certs/mutilated6.pbp`
(a 937-char kernel proof; the single `pol` step is the colour-counting
linear combination).  The mutilated chessboard is exponentially hard for
resolution (Alekhnovich) but easy for cutting planes.  Generated by
`scripts/scaling/gen_mutilated_lean.py`.
-/

/-- The 56 domino-placement variables (one per orthogonally adjacent pair of
    remaining cells), each in `{0,1}`, with a per-cell exactly-one constraint. -/
def mutilatedChessboard6 : IntCSP :=
  ⟨56, ((List.finRange 56).map (fun i => bound i 0 1))
      ++ [
    -- cell (0, 1)
    sum_eq (⟨#[0, 1], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (0, 2)
    sum_eq (⟨#[0, 2, 3], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (0, 3)
    sum_eq (⟨#[2, 4, 5], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (0, 4)
    sum_eq (⟨#[4, 6, 7], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (0, 5)
    sum_eq (⟨#[6, 8], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (1, 0)
    sum_eq (⟨#[9, 10], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (1, 1)
    sum_eq (⟨#[1, 9, 11, 12], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 2)
    sum_eq (⟨#[3, 11, 13, 14], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 3)
    sum_eq (⟨#[5, 13, 15, 16], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 4)
    sum_eq (⟨#[7, 15, 17, 18], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (1, 5)
    sum_eq (⟨#[8, 17, 19], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (2, 0)
    sum_eq (⟨#[10, 20, 21], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (2, 1)
    sum_eq (⟨#[12, 20, 22, 23], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 2)
    sum_eq (⟨#[14, 22, 24, 25], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 3)
    sum_eq (⟨#[16, 24, 26, 27], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 4)
    sum_eq (⟨#[18, 26, 28, 29], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (2, 5)
    sum_eq (⟨#[19, 28, 30], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (3, 0)
    sum_eq (⟨#[21, 31, 32], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (3, 1)
    sum_eq (⟨#[23, 31, 33, 34], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 2)
    sum_eq (⟨#[25, 33, 35, 36], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 3)
    sum_eq (⟨#[27, 35, 37, 38], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 4)
    sum_eq (⟨#[29, 37, 39, 40], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (3, 5)
    sum_eq (⟨#[30, 39, 41], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (4, 0)
    sum_eq (⟨#[32, 42, 43], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (4, 1)
    sum_eq (⟨#[34, 42, 44, 45], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 2)
    sum_eq (⟨#[36, 44, 46, 47], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 3)
    sum_eq (⟨#[38, 46, 48, 49], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 4)
    sum_eq (⟨#[40, 48, 50, 51], rfl⟩ : _root_.Vector (VarType 56) 4) 1,
    -- cell (4, 5)
    sum_eq (⟨#[41, 50], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (5, 0)
    sum_eq (⟨#[43, 52], rfl⟩ : _root_.Vector (VarType 56) 2) 1,
    -- cell (5, 1)
    sum_eq (⟨#[45, 52, 53], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (5, 2)
    sum_eq (⟨#[47, 53, 54], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (5, 3)
    sum_eq (⟨#[49, 54, 55], rfl⟩ : _root_.Vector (VarType 56) 3) 1,
    -- cell (5, 4)
    sum_eq (⟨#[51, 55], rfl⟩ : _root_.Vector (VarType 56) 2) 1
      ]⟩

/-- **UNSAT via the generic pipeline** — the 6 × 6 mutilated chessboard has
    no domino tiling, kernel-checked through PBLean's verified reflection checker
    (discharged by a `Lean.ofReduceBool` term; RoundingSat / veripb / serializer untrusted). -/
theorem mutilated_chessboard_6_unsat :
    ¬ mutilatedChessboard6.isSatisfiableInt :=
  csp_unsat_file mutilatedChessboard6 56 "certs/mutilated6.pbp"

end CSP.L2S.PB.MutilatedChessboard6
