import CSP.L2S.Backends.PB.GenericEncode
import CSP.L2S.Tests.lean.«02_color»

namespace CSP.L2S.PB.OddCycle

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — verified UNSAT for odd-cycle 2-colourability (`c5/c7/c9_2col`)

The odd cycles `C₅`, `C₇`, `C₉` (`Tests/lean/02_color.lean`) are not 2-colourable:
each is a colour variable per vertex over `{1,2}` with a `not_equal` per edge.
Each is discharged by a single `csp_unsat` over its committed certificate
(`certs/`, regenerated by `scripts/gen_cert.sh`); axioms are clean (no `sorryAx`).
-/

/-- **C₅ is not 2-colourable.** -/
theorem c5_2col_unsat : ¬ c5_2col.isSatisfiableInt :=
  csp_unsat_file c5_2col 5 "certs/c5.pbp"

/-- **C₇ is not 2-colourable.** -/
theorem c7_2col_unsat : ¬ c7_2col.isSatisfiableInt :=
  csp_unsat_file c7_2col 7 "certs/c7.pbp"

/-- **C₉ is not 2-colourable.** -/
theorem c9_2col_unsat : ¬ c9_2col.isSatisfiableInt :=
  csp_unsat_file c9_2col 9 "certs/c9.pbp"

end CSP.L2S.PB.OddCycle
