import CSP.L2S.Backends.PB.GenericEncode
import CSP.L2S.Tests.lean.«36_paley»

namespace CSP.L2S.PB.Paley

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — end-to-end verified UNSAT for the Paley-graph corpus CSP `paley_13_4`

The cardinality consumer (`at_most_k` / `at_least_k`) of the pipeline: it
certifies a genuine combinatorial theorem — the **independence number** of the
Paley graph `Paley(13)` is at most `3` — so there is no independent set of size
`4` (`paley_13_4`, `Tests/lean/36_paley.lean`).  Discharged by a single
`csp_unsat` over its committed certificate (`certs/paley_13_4.pbp`, regenerated by
`scripts/gen_cert.sh`); axioms clean (no `sorryAx`).
-/

/-- **`Paley(13)` has no independent set of size 4.** -/
theorem paley_13_4_unsat : ¬ paley_13_4.isSatisfiableInt :=
  csp_unsat_file paley_13_4 13 "certs/paley_13_4.pbp"

end CSP.L2S.PB.Paley
