import CSP.L2S.Backends.PB.GenericEncode
import CSP.L2S.Constraints

namespace CSP.L2S.PB.PeaceableArmies

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — end-to-end verified UNSAT for peaceable armies of queens (n = 4, k = 3)

*Peaceable coexisting armies of queens* asks for the largest `k` such that `k` white and
`k` black queens can be placed on an `n × n` board with no white queen attacking a black
queen.  The optimum on the `4 × 4` board is `a(4) = 2` (OEIS A250000), so `k = 3` is
infeasible — the **tight** UNSAT bound.

## Encoding

`peaceableArmies` uses two Boolean `{0,1}` variables per square — `whiteVar s` (`= s`) and
`blackVar s` (`= 16 + s`), `32` in all — subject to `at_least_k` size bounds per army, a
per-square `at_most_k ≤ 1`, and a per-attacking-pair pair of opposite-colour exclusions.
Every constraint is `at_least_k` / `at_most_k` over `{0,1}`, all supported by the generic
encoder, so the result is one `csp_unsat` over the committed certificate
(`certs/peaceable_4_3.pbp`, regenerated by `scripts/gen_cert.sh`); axioms clean.
-/

/-! ### Variable addressing and the CSP -/

/-- The white-army variable for square `s`: variable index `s`. -/
def whiteVar (s : Fin 16) : Fin 32 := ⟨s.1, by omega⟩

/-- The black-army variable for square `s`: variable index `16 + s`. -/
def blackVar (s : Fin 16) : Fin 32 := ⟨s.1 + 16, by omega⟩

/-- The 76 unordered attacking pairs of squares on the 4×4 board (queen moves:
    same row, column, or diagonal). -/
def paPairs : List (Fin 16 × Fin 16) :=
  [(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 8), (0, 10), (0, 12), (0, 15),
   (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 9), (1, 11), (1, 13),
   (2, 3), (2, 5), (2, 6), (2, 7), (2, 8), (2, 10), (2, 14),
   (3, 6), (3, 7), (3, 9), (3, 11), (3, 12), (3, 15),
   (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 12), (4, 14),
   (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 13), (5, 15),
   (6, 7), (6, 9), (6, 10), (6, 11), (6, 12), (6, 14),
   (7, 10), (7, 11), (7, 13), (7, 15),
   (8, 9), (8, 10), (8, 11), (8, 12), (8, 13),
   (9, 10), (9, 11), (9, 12), (9, 13), (9, 14),
   (10, 11), (10, 13), (10, 14), (10, 15),
   (11, 14), (11, 15), (12, 13), (12, 14), (12, 15),
   (13, 14), (13, 15), (14, 15)]

/-- Scope of the white-army cardinality constraint: variables `0 .. 15`. -/
def paWhiteScope : _root_.Vector (VarType 32) 16 :=
  ⟨#[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], rfl⟩

/-- Scope of the black-army cardinality constraint: variables `16 .. 31`. -/
def paBlackScope : _root_.Vector (VarType 32) 16 :=
  ⟨#[16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], rfl⟩

/-- One `at_most_k ≤ 1` per square: at most one queen (of either colour) per square. -/
def paDisjointC : List (IntConstraint 32) :=
  (List.finRange 16).map (fun s =>
    at_most_k (⟨#[whiteVar s, blackVar s], rfl⟩ :
      _root_.Vector (VarType 32) 2) 1)

/-- Per attacking pair, the two opposite-colour exclusions. -/
def paPairwiseC : List (IntConstraint 32) :=
  paPairs.flatMap (fun p =>
    [at_most_k (⟨#[whiteVar p.1, blackVar p.2], rfl⟩ :
        _root_.Vector (VarType 32) 2) 1,
     at_most_k (⟨#[blackVar p.1, whiteVar p.2], rfl⟩ :
        _root_.Vector (VarType 32) 2) 1])

/-- Peaceable armies (n = 4, k = 3) as a `IntCSP`. -/
def peaceableArmies : IntCSP :=
  ⟨32, ((List.finRange 32).map (fun i => bound i 0 1))
      ++ [at_least_k paWhiteScope 3, at_least_k paBlackScope 3]
      ++ paDisjointC ++ paPairwiseC⟩

/-- **Peaceable armies (4×4, k = 3) is infeasible** — `a(4) = 2`. -/
theorem peaceable_armies_4_3_unsat : ¬ peaceableArmies.isSatisfiableInt :=
  csp_unsat_file peaceableArmies 32 "certs/peaceable_4_3.pbp"

end CSP.L2S.PB.PeaceableArmies
