import CSP.L2S.Backends.PB.GenericEncode
import CSP.L2S.Tests.lean.«19_sudoku»

namespace CSP.L2S.PB.Sudoku

open CSP.L2S CSP.L2S.PB

/-!
# PB backend — end-to-end verified UNSAT for a Sudoku with contradictory givens

The `equals_const` (fixed-value / "givens") consumer of the pipeline.  The corpus
parametric puzzle `sudoku_csp` (`Tests/lean/19_sudoku.lean`) is satisfiable with no
clues, so we form `sudoku_4_contradictory` by adding two clues that violate a rule:
a 4×4 grid (domain `{1,2,3,4}`) with the first two cells of row 0 both clued to `1`.
Two equal entries in one row contradict that row's `alldifferent`, so the puzzle is
unsatisfiable — discharged by a single `csp_unsat` over its committed certificate
(`certs/sudoku_4.pbp`, regenerated by `experiments/gen_cert.py`); axioms clean.
-/

/-- The contradictory-clue instance: the corpus 4×4 Sudoku (`sudoku_4`) with two clues
    that both pin row 0's first two cells (variables 0 and 1) to the digit `1`, violating
    row 0's `alldifferent`. -/
def sudoku_4_contradictory : IntCSP :=
  sudoku_4.addConstraints [equals_const ⟨0, by decide⟩ 1, equals_const ⟨1, by decide⟩ 1]

/-- **The contradictory-clue Sudoku is unsatisfiable.** -/
theorem sudoku_4_contradictory_unsat : ¬ sudoku_4_contradictory.isSatisfiableInt :=
  csp_unsat_file sudoku_4_contradictory 48 "certs/sudoku_4.pbp"

end CSP.L2S.PB.Sudoku
